// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzthdzkjcrhxbqkzlcxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dGhkemtqY3JoeGJxa3psY3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjY5OTAsImV4cCI6MjA2MDE0Mjk5MH0.bQFMOxvoFZWNfLkgnR7huOS5JyeYr6sjX5SlIkCMSJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);